dist: trusty
language: cpp

matrix:
  include:
  - os: linux
    language: cpp
    compiler: gcc
    env: COMPILER="g++-7" CXX_STANDARD=14
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:mhier/libboost-latest'
        packages:
        - g++-7
        - boost1.70
  - os: linux
    language: cpp
    compiler: clang
    env: COMPILER="clang++-6.0" CXX_STANDARD=14
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:mhier/libboost-latest'
        - llvm-toolchain-trusty-6.0
        packages:
        - clang-6.0
        - boost1.70
  - os: osx
    language: cpp
    compiler: clang
    env: COMPILER="clang++" CXX_STANDARD=14

script:
- |
  if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
    mkdir -p cmake
    travis_retry wget "https://cmake.org/files/v3.11/cmake-3.11.2-Linux-x86_64.tar.gz"
    tar xf cmake-3.11.2-Linux-x86_64.tar.gz -C cmake --strip-components=1
    export PATH=${TRAVIS_BUILD_DIR}/cmake/bin:${PATH}
  else
    brew upgrade boost cmake
  fi
- cmake --version
- mkdir build
- cd build
- cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_CXX_STANDARD=$CXX_STANDARD -DFIND_BOOST=ON ..
- make
- ctest --output-on-failure
